---
title: "Parallelization with RNGs in C++"
subtitle: "Exploration of `static thread_local`.." 
author: "James Balamuta"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{threadlocal_random}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This research note explores using `static local` and the `dqrng` package.
That said, the same results generalize to using 
[`std::default_random_engine`](http://www.cplusplus.com/reference/random/default_random_engine/).

```{r}
# Obtain 50 different RNG samples of size 100,000
rng_sample = replicate(50, { RcppRNGParallel::draw_numeric_unif(1e5) })
rng_sample
# Obtain correlation
cor_matrix = cor(rng_sample)

if(requireNamespace("reshape2", quietly = TRUE) &
   requireNamespace("ggplot2", quietly = TRUE)) {
  # To long-form
  long_cor_matrix = reshape2::melt(cor_matrix)
  
  # Plot with ggplot2
  ggplot2::ggplot(data = long_cor_matrix) +
    ggplot2::aes(x = Var1, y = Var2, fill = value) +
    ggplot2::geom_tile() +
    ggplot2::labs(
      title = "Correlation between streams",
      subtitle = "Light is highly correlated, dark is uncorrelated",
      caption = "Parallelized RNG via dqrng and OpenMP, @coatless",
      fill = "Correlation",
      x = "Stream R1",
      y = "Stream R2"
    ) + ggplot2::theme_minimal()
}
```

