# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Max CPU cores
#'
#' Determine the number of cores available
#'
#' @return
#' Integer containing the maximum number of CPU cores.
#'
#' If 0, then parallelization is not supported and a silent failure occurs
#'
#' @export
#' @examples
#'
#' # Retrieve the number of total cores on the machine.
#' max_cores()
max_cores <- function() {
    .Call(`_RcppRNGParallel_max_cores`)
}

#' Static Thread Local Parallelized Uniform RNG sampler
#'
#' Samples from the Uniform distribution in parallel through using
#' core specific RNG engines that are kept active throughout the calculation.
#'
#' @param n    Number of values to generate.
#' @param min  Bottom value to generate values from in a continuous uniform.
#' @param max  Top range to generate values from in a continuous uniform.
#'
#' @return
#' A `numeric` vector containing the output.
#'
#' @export
#' @examples
#' # Retrieves 100 observations from a random uniform distribution.
#' x = draw_numeric_unif(100)
draw_numeric_unif <- function(n, min = 0.0, max = 1.0) {
    .Call(`_RcppRNGParallel_draw_numeric_unif`, n, min, max)
}

